// src/components/category/Category.tsx
import { useNavigate } from "react-router-dom";
import { formatTitleCase } from "../../utils/format";
import type { Category as CategoryType } from "../../interfaces/category.interface";
import "./Category.css";

interface CategoryProps {
  category: CategoryType;
}

function Category({ category }: CategoryProps) {
  const navigate = useNavigate();

  const onSelect = () => {
    navigate(`/quiz/${category.name}`);
  };

  const cardClass = `card category-card category-card${category.id % 6}`;
  const iconClass = `material-icons mat-icon${category.id % 6}`;

  return (
    <>
      <div className={cardClass} onClick={onSelect}>
        <div className="card-body text-center">
          <i className={iconClass}>{category.icon}</i>
          <h3>{formatTitleCase(category.name)}</h3>
          <p className="description">{category.description}</p>
        </div>
      </div>
    </>
  );
}

export default Category;

// src/app/category/category.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { Category } from '../interfaces/category.interface';

@Component({
  selector: 'app-category',
  standalone: true,
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.css'],
  imports: [CommonModule, MatCardModule, MatIconModule],
})
export class CategoryComponent {
  @Input() category!: Category;


  constructor(private router: Router) { }

  onSelect(): void {
    this.router.navigate(['/quiz', this.category.name]);
  }


}
<mat-card class="category-card category-card{{ category.id }}" (click)="onSelect()">
  <mat-card-content>
    <mat-icon>{{ category.icon }}</mat-icon>
    <h3>{{ category.name | titlecase }}</h3>
    <p class="description">{{ category.description }}</p>
  </mat-card-content>
</mat-card>
