// src/app/components/leaderboard/leaderboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { QuizService } from '../../services/quiz.service';
import { FormsModule } from '@angular/forms';
import { Score } from '../../interfaces/score.interface';
import { Category } from '../../interfaces/category.interface';
import { ChartComponent } from "../chart/chart.component";

@Component({
  selector: 'app-leaderboard',
  standalone: true,
  templateUrl: './leaderboard.component.html',
  styleUrl: './leaderboard.component.css',
  imports: [CommonModule, FormsModule, ChartComponent],
})
export class LeaderboardComponent implements OnInit {

  scores: Score[] = [];
  categories: Category[] = [];
  currentCategoryId!: number;
  selectedCategory: string = '';

  constructor(
    private quizService: QuizService, 
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.quizService.getCategories().subscribe((data) => {
      this.categories = data;
      
      this.route.paramMap.subscribe(params => {
        const categoryName = params.get('category');
        if (categoryName) {
          this.selectedCategory = categoryName;
          const foundCategory = data.find(c => c.name === categoryName);
          if (foundCategory) {
            this.currentCategoryId = foundCategory.id;
          }
          this.loadScores();
        }
      });
    });
  }

  loadScores(): void {
    this.quizService.getScoresByCategory(this.selectedCategory).subscribe((data) => {
      this.scores = data.sort((a, b) => b.score - a.score);
    });
  }

  onCategoryChange(): void {
    this.router.navigate(['/leaderboard', this.selectedCategory]).then(() => {
      window.scrollTo(0, 0);
    });
  }

  scrollToTop(): void {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

<div class="leaderboard-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10">
        <div class="card leaderboard-main-card shadow border-0">

          <!-- Leaderboard Header -->
          <div class="leaderboard-header">
            <h1>Leaderboard: {{ selectedCategory | titlecase }}</h1>
          </div>

          <div class="chart-style">
            <app-chart></app-chart>
          </div>

          <div class="leaderboard-content">
            @if (categories.length > 0) {

            <!-- Category Selector -->
            <div class="category-selector">
              <label for="category">Select a category:</label>
              <select id="category" class="form-select" [(ngModel)]="selectedCategory" (change)="onCategoryChange()">
                @for (category of categories; track category.name) {
                <option [value]="category.name">{{ category.name | titlecase }}</option>
                }
              </select>
            </div>

            <!-- Leaderboard Table -->
            @if (scores.length > 0) {
            <div class="table-container">
              <div class="table-responsive">
                <table class="table table-hover mb-0">
                  <thead>
                    <tr>
                      <th scope="col" class="text-center">#</th>
                      <th scope="col" class="text-center">Player</th>
                      <th scope="col" class="text-center">Score</th>
                      <th scope="col" class="text-center">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    @for (score of scores; let i = $index; track score) {
                    <tr>
                      <td class="position-cell text-center">{{ i + 1 }}</td>
                      <td class="username-cell text-center"><strong>{{ score.username }}</strong></td>
                      <td class="text-center">
                        <span [class]="'badge-' + currentCategoryId%6" class="badge score-badge">{{ score.score
                          }}</span>
                      </td>
                      <td class="date-cell text-center">{{ score.date | date:'dd/MM/yyyy' }}</td>
                    </tr>
                    }
                  </tbody>
                </table>
              </div>
            </div>
            }

            <!-- Back to Top Button -->
            <div class="back-to-top">
              <button type="button" class="btn btn-light" (click)="scrollToTop()">
                <i class="material-icons">keyboard_arrow_up</i>
                Back to top
              </button>
            </div>

            }
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

// src/components/leaderboard/Leaderboard.tsx
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getCategories, getScoresByCategory } from "../../services/quiz.service";
import type { Category as CategoryType } from "../../interfaces/category.interface";
import type { Score } from "../../interfaces/score.interface";
import "./Leaderboard.css";
import { formatTitleCase } from "../../utils/format";
import Chart from "../chart/Chart";

function Leaderboard() {
  const { category } = useParams<{ category: string }>();
  const navigate = useNavigate();

  const [categories, setCategories] = useState<CategoryType[]>([]);
  const [scores, setScores] = useState<Score[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<string>(category || "");
  const [currentCategoryId, setCurrentCategoryId] = useState<number>(0);

  // Carica categorie e aggiorna categoria selezionata
  useEffect(() => {
    getCategories().then((data) => {
      setCategories(data);
      if (selectedCategory) {
        const found = data.find((c) => c.name === selectedCategory);
        if (found) setCurrentCategoryId(found.id);
      }
    });
  }, [selectedCategory]);

  // Aggiorna categoria selezionata quando cambia il parametro nell'URL
  useEffect(() => {
    if (category) {
      setSelectedCategory(category);
      const found = categories.find((c) => c.name === category);
      if (found) setCurrentCategoryId(found.id);
    }
  }, [category, categories]);

  // Carica punteggi quando cambia la categoria selezionata
  useEffect(() => {
    if (selectedCategory) {
      getScoresByCategory(selectedCategory).then((data) => {
        setScores([...data].sort((a, b) => b.score - a.score));
      });
    }
  }, [selectedCategory]);

  function handleCategoryChange(e: React.ChangeEvent<HTMLSelectElement>) {
    const newCategory = e.target.value;
    setSelectedCategory(newCategory);
    navigate(`/leaderboard/${newCategory}`);
  }

  function scrollToTop() {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  const badgeClass = `badge score-badge badge-${currentCategoryId % 6}`;

  return (
    <div className="leaderboard-container">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-12 col-lg-10">
            <div className="card leaderboard-main-card shadow border-0">

              {/* Leaderboard Header */}
              <div className="leaderboard-header">
                <h1>Leaderboard: {formatTitleCase(selectedCategory)}</h1>
              </div>

              <div className="chart-style">
                <Chart />
              </div>

              <div className="leaderboard-content">
                {/* Category Selector */}
                {categories.length > 0 && (
                  <div className="category-selector">
                    <label htmlFor="category">Select a category:</label>
                    <select
                      id="category"
                      className="form-select"
                      value={selectedCategory}
                      onChange={handleCategoryChange}
                    >
                      {categories.map((category) => (
                        <option key={category.id} value={category.name}>
                          {formatTitleCase(category.name)}
                        </option>
                      ))}
                    </select>
                  </div>
                )}

                {/* Leaderboard Table */}
                {scores.length > 0 && (
                  <div className="table-container">
                    <div className="table-responsive">
                      <table className="table table-hover mb-0">
                        <thead>
                          <tr>
                            <th scope="col" className="text-center">#</th>
                            <th scope="col" className="text-center">Player</th>
                            <th scope="col" className="text-center">Score</th>
                            <th scope="col" className="text-center">Date</th>
                          </tr>
                        </thead>
                        <tbody>
                          {scores.map((score, i) => (
                            <tr key={score.id}>
                              <td className="position-cell text-center">{i + 1}</td>
                              <td className="username-cell text-center"><strong>{score.username}</strong></td>
                              <td className="text-center">
                                <span className={badgeClass}>
                                  {score.score}
                                </span>
                              </td>
                              <td className="date-cell text-center">
                                {new Date(score.date).toLocaleDateString()}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

                <div className="back-to-top mt-4">
                  <button type="button" className="btn btn-light" onClick={scrollToTop}>
                    <i className="material-icons">keyboard_arrow_up</i>
                    Back to top
                  </button>
                </div>

              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Leaderboard;
