// src/app/timer/timer.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { ProgressBarModule } from 'primeng/progressbar';

@Component({
  selector: 'app-timer',
  standalone: true,
  imports: [CommonModule, ProgressBarModule, DatePipe],
  templateUrl: './timer.component.html',
  styleUrls: ['./timer.component.css']
})
export class TimerComponent implements OnInit, OnDestroy {
  @Input() duration = 120;
  @Input() categoryId!: number;
  @Output() timeExpired = new EventEmitter<void>();
  @Output() timeUpdate = new EventEmitter<number>();

  progress = 100;
  currentTime: number = 0;
  private intervalId: any;
  private isRunning = false;

  ngOnInit(): void {
    this.startTimer();
  }

  private startTimer(): void {
    if (this.isRunning) return;
    
    this.isRunning = true;
    this.currentTime = this.duration;
    
    this.intervalId = setInterval(() => {
      this.currentTime--;
      this.progress = (this.currentTime / this.duration) * 100;
      
      this.timeUpdate.emit(this.currentTime);

      if (this.currentTime <= 0) {
        this.stopTimer();
        this.timeExpired.emit();
      }
    }, 1000);
  }

  stopTimer(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
      this.isRunning = false;
    }
  }

  resetTimer(): void {
    this.progress = 100;
    this.currentTime = this.duration;
    this.startTimer();
  }


  getRemainingTime(): number {
    return this.currentTime;
  }

  ngOnDestroy(): void {
    this.stopTimer();
  }
}
<div class="timer-container">
  <div class="countdown-display time-value{{ categoryId }}">
      {{ (currentTime * 1000) | date:'mm:ss':'UTC' }}
  </div>

  <p-progressBar [value]="progress" [style]="{ 'height': '12px' }" [styleClass]="'category-' + categoryId"
    [showValue]="false"></p-progressBar>
</div>

// src/components/timer/Timer.tsx
import { useState, useEffect, useRef } from 'react';
import { ProgressBar } from 'primereact/progressbar';
import { formatTime } from '../../utils/format';
import "./Timer.css";

interface TimerProps {
  duration: number;
  categoryId: number;
  onTimeExpired: () => void;
  onTimeUpdate: (remainingTime: number) => void;
  onShowModal: (show: boolean) => void;
}

function Timer({ duration, categoryId, onTimeExpired, onTimeUpdate, onShowModal }: TimerProps) {
  const [currentTime, setCurrentTime] = useState(duration);
  const [progress, setProgress] = useState(100);
  const intervalId = useRef<number | null>(null);
  const isRunning = useRef(false);

  useEffect(() => {
    startTimer();
    return () => stopTimer();
  }, [duration]);

  const startTimer = () => {
    if (isRunning.current) return;
    isRunning.current = true;
    setCurrentTime(duration);

    intervalId.current = window.setInterval(() => {
      setCurrentTime((prevTime) => {
        const newTime = prevTime - 1;
        onTimeUpdate(newTime);

        if (newTime <= 0) {
          stopTimer();
          onTimeExpired();
          onShowModal(true);
          return 0;
        }
        return newTime;
      });
    }, 1000);
  };

  const stopTimer = () => {
    if (intervalId.current !== null) {
      window.clearInterval(intervalId.current);
      intervalId.current = null;
      isRunning.current = false;
    }
  };

  useEffect(() => {
    setProgress((currentTime / duration) * 100);
  }, [currentTime, duration]);

  return (
    <div className="timer-container">
      <div className={`countdown-display time-value${categoryId % 6}`}>
        {formatTime(currentTime)}
      </div>
      <ProgressBar
        value={progress}
        className={`category-${categoryId % 6}`}
        showValue={false}
      />
    </div>
  );
}

export default Timer;
