// src/app/components/quiz/quiz.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { MatDialogModule } from '@angular/material/dialog';
import { MatDialog } from '@angular/material/dialog';
import {MatTooltipModule} from '@angular/material/tooltip';
import { TimeoutComponent } from '../timeout/timeout.component';
import { PaginatorComponent } from '../paginator/paginator.component';
import { TimerComponent } from '../timer/timer.component';
import { Question } from '../../interfaces/question.interface';
import { QuizService } from '../../services/quiz.service';

@Component({
  selector: 'app-quiz',
  standalone: true,
  templateUrl: './quiz.component.html',
  styleUrl: './quiz.component.css',
  imports: [
    CommonModule,
    PaginatorComponent,
    TimerComponent,
    MatDialogModule,
    MatTooltipModule
  ],
})
export class QuizComponent implements OnInit {
  @ViewChild('quizTimer') timerComponent!: TimerComponent;

  questions: Question[] = [];
  currentQuestionIndex = 0;
  currentCategoryId!: number;
  selectedCategory: string = '';

  correctAnswers = 0;
  finalScore = 0;
  remainingTime = 0;
  isQuizCompleted = false;
  allQuestionsAnswered = false;

  showModal: boolean = false;

  constructor(
    private quizService: QuizService,
    private route: ActivatedRoute,
    private router: Router,
    private dialog: MatDialog
  ) { }

  ngOnInit(): void {
    this.quizService.getCategories().subscribe((data) => {
      this.route.paramMap.subscribe(params => {
        const categoryName = params.get('category');
        if (categoryName) {
          this.selectedCategory = categoryName;
          const foundCategory = data.find(c => c.name === categoryName);
          if (foundCategory) {
            this.currentCategoryId = foundCategory.id;
          }
          this.loadCategory(this.selectedCategory);
        }
      });
    });
  }

  loadCategory(category: string): void {
    this.quizService.getQuestionsByCategory(category).subscribe((data) => {
      const shuffled = this.shuffleArray([...data]);
      this.questions = shuffled.slice(0, 10);
      this.questions.forEach(q => q.currentAnswer = null);
    });
  }

  shuffleArray(array: any[]): any[] {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
  }

  get currentQuestion(): Question | null {
    return this.questions[this.currentQuestionIndex] ?? null;
  }

  onPageChange(index: number): void {
    this.currentQuestionIndex = index;
  }

  selectAnswer(optionIndex: number): void {
    if (this.currentQuestion && !this.isQuizCompleted) {
      this.currentQuestion.currentAnswer = optionIndex;
      this.checkAllQuestionsAnswered();
    }
  }

  checkAllQuestionsAnswered(): void {
    this.allQuestionsAnswered = this.questions.every(q => q.currentAnswer !== null);
  }

  getAnsweredQuestionsIndices(): number[] {
    return this.questions
      .map((question, index) => question.currentAnswer !== null ? index : -1)
      .filter(index => index !== -1);
  }

  updateRemainingTime(seconds: number): void {
    this.remainingTime = seconds;
  }

  handleTimeExpired(): void {
    this.finishQuiz();

    this.dialog.open(TimeoutComponent, {
      width: '400px',
      disableClose: true
    });
  }

  finishQuiz(): void {
    if (this.isQuizCompleted) return;

    this.isQuizCompleted = true;
    this.timerComponent?.stopTimer();
    this.calculateScore();
    this.navigateToResults();
  }

  calculateScorePoints(correctAnswers: number, remainingTime: number): number {
    const correctnessPoints = correctAnswers * 70;
    const timeBonus = remainingTime * correctAnswers * 0.3;

    if (correctnessPoints > 0) {
      return Math.round(correctnessPoints + timeBonus);
    }
    else {
      return 0;
    }
  }

  calculateScore(): void {
    this.correctAnswers = this.questions.filter(q =>
      q.currentAnswer === q.correctOptionIndex
    ).length;

    this.finalScore = this.calculateScorePoints(
      this.correctAnswers,
      Math.max(0, this.remainingTime)
    );
  }

  navigateToResults(): void {
    this.router.navigate(['/results', this.selectedCategory], {
      state: {
        questions: this.questions,
        correctAnswers: this.correctAnswers,
        finalScore: this.finalScore,
        remainingTime: this.remainingTime,
        selectedCategory: this.selectedCategory,
        currentCategoryId: this.currentCategoryId
      }
      }).then(() => {
      window.scrollTo(0, 0);
    });
  }

}
<div class="quiz-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10">
        <div class="card quiz-main-card shadow border-0">

          <!-- Quiz Header -->
          <div class="quiz-header">
            <h1>{{ selectedCategory | titlecase }} Quiz</h1>
          </div>

          <div class="quiz-content">
            @if (questions.length > 0) {
            <!-- Timer Component -->
            <div class="quiz-timer">
              <app-timer [duration]="120" [categoryId]="currentCategoryId" (timeExpired)="handleTimeExpired()"
                (timeUpdate)="updateRemainingTime($event)" #quizTimer>
              </app-timer>
            </div>
            }

            <!-- Mostra domanda durante il quiz -->
            @if (currentQuestion) {
            <div class="quiz-question-container">
              <h2>Question {{ currentQuestionIndex + 1 }} of {{ questions.length }}</h2>
              <p class="question-text">{{ currentQuestion.question }}</p>

              <div class="options-container">
                @for (option of currentQuestion.options; track $index) {
                <div class="card option-card" [class.selected]="currentQuestion.currentAnswer === $index"
                  [class]="'option-card-' + currentCategoryId%6" (click)="selectAnswer($index)">
                  <div class="card-body">
                    {{ option }}
                  </div>
                </div>
                }
              </div>
            </div>
            }

            <!-- Paginator Component -->
            @if (questions.length > 0) {
            <div class="quiz-paginator">
              <app-paginator [total]="questions.length" [current]="currentQuestionIndex"
                [categoryId]="currentCategoryId" [answeredQuestions]="getAnsweredQuestionsIndices()"
                (change)="onPageChange($event)">
              </app-paginator>
            </div>
            }
          </div>

          <!-- Pulsante Fine Quiz -->
          @if (currentQuestion) {
            <div class="quiz-actions">
            <button type="button" class="btn btn-light" [disabled]="!allQuestionsAnswered" (click)="finishQuiz()">
              <span matTooltip="You must answer all questions before finishing the quiz"
                [matTooltipDisabled]="allQuestionsAnswered"
                matTooltipPosition="above"
                aria-label="Button that displays a tooltip when focused or hovered over"
                style="pointer-events: auto;">
                Finish Quiz
                </span>
            </button>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</div>

// src/components/quiz/Quiz.tsx
import { useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import type { RootState } from "../../redux/store";
import {
  setQuestions,
  setCurrentCategory,
  setCurrentQuestionIndex,
  selectAnswer,
  updateRemainingTime,
  finishQuiz,
  resetQuiz,
} from "../../redux/quizSlice";
import { getCategories, getQuestionsByCategory } from "../../services/quiz.service";
import type { Question as QuestionType } from "../../interfaces/question.interface";
import { formatTitleCase } from "../../utils/format";
import Paginator from "../paginator/Paginator";
import Timer from "../timer/Timer";
import "./Quiz.css";
import Tooltip from '@mui/material/Tooltip';

function Quiz() {
  const { category } = useParams<{ category: string }>(); // prendo categoria da url
  const navigate = useNavigate();
  const dispatch = useDispatch();

  // prende i dati dallo store redux
  const {
    questions,
    currentQuestionIndex,
    currentCategoryId,
    selectedCategory,
    isQuizCompleted,
    allQuestionsAnswered,
    correctAnswers,
    finalScore,
    remainingTime,
  } = useSelector((state: RootState) => state.quiz);

  // useEffect per caricare i dati (come nel componente Home)
  useEffect(() => {
    if (!category) return;

    // Reset del quiz quando cambia categoria
    dispatch(resetQuiz());

    // Carica categorie e trova quella corrente
    getCategories().then((data) => {
      const found = data.find((c) => c.name === category);
      if (found) {
        dispatch(setCurrentCategory({ name: category, id: found.id }));
      }
    });

    // Carica domande e randomizza array
    getQuestionsByCategory(category).then((data: QuestionType[]) => {
      const shuffled = shuffleArray([...data]).slice(0, 10);
      shuffled.forEach((q) => (q.currentAnswer = null));
      dispatch(setQuestions(shuffled));
    });
  }, [category, dispatch]);

  function shuffleArray(array: any[]): any[] {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
  }

  const currentQuestion = questions[currentQuestionIndex];

  // Gestione selezione risposta
  function handleSelect(answerIndex: number) {
    if (!isQuizCompleted && currentQuestion) {
      dispatch(selectAnswer({
        questionIndex: currentQuestionIndex,
        answerIndex,
      }));
    }
  }

  // Gestione cambio pagina
  function handlePageChange(index: number) {
    dispatch(setCurrentQuestionIndex(index));
  }

  // Gestione aggiornamento timer
  function handleTimeUpdate(seconds: number) {
    dispatch(updateRemainingTime(seconds));
  }
  // Gestione fine tempo
  function handleTimeExpired() {
    handleFinishQuiz();
    // modal timeout
  }

  // Calcola indici domande risposte
  function getAnsweredQuestionsIndices(): number[] {
    return questions
      .map(function (question: QuestionType, index: number) {
        return question.currentAnswer !== null ? index : -1;
      })
      .filter(function (index: number) {
        return index !== -1;
      });
  }

  // Gestione fine quiz
  function handleFinishQuiz() {
    if (isQuizCompleted) return;

    dispatch(finishQuiz());

    // Naviga ai risultati
    navigate(`/results/${category}`, {
      state: {
        questions,
        correctAnswers,
        finalScore,
        remainingTime,
        selectedCategory: category,
        currentCategoryId,
      },
    });
  };

  return (
    <div className="quiz-container">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-12 col-lg-10">
            <div className="card quiz-main-card shadow border-0">

              <div className="quiz-header">
                <h1>
                  {formatTitleCase(selectedCategory)} Quiz
                </h1>
              </div>

              <div className="quiz-content">
                {questions.length > 0 && (
                  <div className="quiz-timer">
                    <Timer
                    /*                       duration={120}
                                          categoryId={currentCategoryId || 0}
                                          onTimeExpired={handleTimeExpired}
                                          onTimeUpdate={handleTimeUpdate} */
                    />
                  </div>
                )}

                {currentQuestion && (
                  <div className="quiz-question-container">
                    <h2>
                      Question {currentQuestionIndex + 1} of {questions.length}
                    </h2>
                    <p className="question-text">{currentQuestion.question}</p>

                    <div className="options-container">
                      {currentQuestion.options.map((option, i) => {
                        const optionClass = `card option-card ${currentQuestion.currentAnswer === i ? "selected" : ""}
                          option-card-${currentCategoryId && currentCategoryId % 6}`;
                        return (
                          <div
                            key={i}
                            className={optionClass}
                            onClick={() => handleSelect(i)}
                          >
                            <div className="card-body">{option}</div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                {questions.length > 0 && (
                  <div className="quiz-paginator">
                    <Paginator
                      total={questions.length}
                      current={currentQuestionIndex}
                      categoryId={currentCategoryId || 0}
                      answeredQuestions={getAnsweredQuestionsIndices()}
                      onChange={handlePageChange}
                    />
                  </div>
                )}
              </div>
              {currentQuestion && (
                <div className="quiz-actions">
                  {allQuestionsAnswered ? (
                    <button
                      className="btn btn-light"
                      onClick={handleFinishQuiz}
                      disabled={false}
                    >
                      Finish Quiz
                    </button>
                  ) : (
                    <Tooltip title="You must answer all questions before finishing the quiz" followCursor>
                      <div className="button-tooltip">
                        <button
                          className="btn btn-light"
                          onClick={handleFinishQuiz}
                          disabled
                        >
                          Finish Quiz
                        </button>
                      </div>
                    </Tooltip>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Quiz;
