// src/app/components/category/category.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { Category } from '../../interfaces/category.interface';

@Component({
  selector: 'app-category',
  standalone: true,
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.css'],
  imports: [CommonModule, MatCardModule, MatIconModule],
})
export class CategoryComponent {
  @Input() category!: Category;

  constructor(private router: Router) { }

  onSelect(): void {
    this.router.navigate(['/quiz', this.category.name], {
    });
  }
  
  onCardKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.onSelect();
    }
  }
}
<div
  class="card category-card category-card{{ category.id%6 }}"
  tabindex="0"
  role="button"
  (click)="onSelect()"
  (keydown)="onCardKeydown($event)"
  [attr.aria-label]="'Select category ' + category.name"
>
  <div class="card-body">
    <i class="material-icons mat-icon{{ category.id%6 }}" aria-hidden="true">{{ category.icon }}</i>
    <h3>{{ category.name | titlecase }}</h3>
    <p class="description">{{ category.description }}</p>
  </div>
</div>

// src/components/category/Category.tsx
import { useNavigate } from "react-router-dom";
import { formatTitleCase } from "../../utils/format";
import type { Category as CategoryType } from "../../interfaces/category.interface";
import "./Category.css";

interface CategoryProps {
  category: CategoryType;
}

function Category({ category }: CategoryProps) {
  const navigate = useNavigate();

  const onSelect = () => {
    navigate(`/quiz/${category.name}`);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      onSelect();
    }
  };

  const cardClass = `card category-card category-card${category.id % 6}`;
  const iconClass = `material-icons mat-icon${category.id % 6}`;

  return (
    <div
      className={cardClass}
      onClick={onSelect}
      tabIndex={0}
      role="button"
      aria-label={`Select category ${formatTitleCase(category.name)}`}
      onKeyDown={handleKeyDown}
    >
      <div className="card-body text-center">
        <i className={iconClass}>{category.icon}</i>
        <h3>{formatTitleCase(category.name)}</h3>
        <p className="description">{category.description}</p>
      </div>
    </div>
  );
}

export default Category;
