// src/components/chart/Chart.tsx
import { useEffect, useState } from "react";
import { BarChart } from "@mui/x-charts/BarChart";
import { axisClasses } from "@mui/x-charts";
import { getAllScores } from "../../services/score.service";
import { getCategories } from "../../services/quiz.service";
import "./Chart.css";

const min = 0;
const max = 1000;
const step = 100;

function generateScoreRanges(min: number, max: number, step: number): string[] {
  const ranges: string[] = [];
  for (let i = min; i < max; i += step) {
    ranges.push(`${i}-${i + step}`);
  }
  return ranges;
}

function getCSSColors(): string[] {
  const colors: string[] = [];
  for (let i = 0; i < 6; i++) {
    const color = getComputedStyle(document.documentElement)
      .getPropertyValue(`--category-color-${i}`)
      .trim();
    colors.push(color);
  }
  return colors;
}

export default function Chart() {
  const [barData, setBarData] = useState<any[]>([]);
  const [labels, setLabels] = useState<string[]>([]);
  const [scores, setScores] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);

  useEffect(() => {
    getCategories().then(setCategories);
  }, []);

  useEffect(() => {
    getAllScores().then(setScores);
  }, []);

  useEffect(() => {
    if (categories.length === 0 || scores.length === 0) return;

    const scoreRanges = generateScoreRanges(min, max, step);
    setLabels(scoreRanges);

    const dataPerCategory: Record<string, number[]> = {};
    categories.forEach((cat: any) => {
      dataPerCategory[cat.name] = new Array((max - min) / step).fill(0);
    });

    scores.forEach((score: any) => {
      const rangeIndex = Math.floor(score.score / step);
      const index = Math.min(rangeIndex, (max - min) / step - 1);
      if (dataPerCategory[score.category]) {
        dataPerCategory[score.category][index]++;
      }
    });

    const colors = getCSSColors();

    const datasets = categories.map((cat: any, i: number) => ({
      label: cat.name.charAt(0).toUpperCase() + cat.name.slice(1),
      data: dataPerCategory[cat.name],
      color: colors[i % colors.length],
    }));

    setBarData(datasets);
  }, [categories, scores]);

  const chartSetting = {
    yAxis: [
      {
        label: "Number of players",
      },
    ],
    width: 1000,
    height: 400,
    sx: {
      [`.${axisClasses.left} .${axisClasses.label}`]: {
        transform: "translate(-20px, 0)",
      },
    },
  };

  return (
      <BarChart
        {...chartSetting}
        series={barData.map(ds => ({
          data: ds.data,
          label: ds.label,
          color: ds.color,
        }))}
        xAxis={[{ data: labels, label: "Score ranges" }]}
      />
  );
}

// src/app/components/chart/chart.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { BaseChartDirective } from 'ng2-charts';
import { ChartConfiguration } from 'chart.js';
import { ScoreService } from '../../services/score.service';
import { QuizService } from '../../services/quiz.service';
import { Category } from '../../interfaces/category.interface';
import { Score } from '../../interfaces/score.interface';

@Component({
  selector: 'app-chart',
  imports: [BaseChartDirective],
  templateUrl: './chart.component.html',
  styleUrl: './chart.component.css'
})
export class ChartComponent implements OnInit {
  public barChartData: ChartConfiguration<'bar'>['data'] = {
    labels: [],
    datasets: []
  };

  public barChartOptions: ChartConfiguration<'bar'>['options'] = {
    responsive: true,
    plugins: {
      legend: {
        display: true,
        position: 'top'
      }
    },
    scales: {
      x: {
        stacked: false,
        title: {
          display: true,
          text: 'Score ranges'
        }
      },
      y: {
        beginAtZero: true,
        stacked: false,
        title: {
          display: true,
          text: 'Number of players'
        },
        ticks: {
          stepSize: 1,
        }
      }
    }
  };

  scores: Score[] = [];
  categories: Category[] = [];

  constructor(private scoreService: ScoreService, private quizService: QuizService) { }

  ngOnInit(): void {
    this.loadAllScores();
  }

  loadAllScores(): void {
    this.scoreService.getAllScores().subscribe((data: Score[]) => {
      this.scores = data;
      this.generateHistogramData();
    });
  }

  generateScoreRanges(min: number, max: number, step: number): string[] {
    const ranges: string[] = [];
    for (let i = min; i < max; i += step) {
      ranges.push(`${i}-${i + step}`);
    }
    return ranges;
  }

  getCSSColors(): { backgroundColor: string[], borderColors: string[] } {
    const backgroundColors: string[] = [];
    const borderColors: string[] = [];

    for (let i = 0; i < 6; i++) {
      const bgColor = getComputedStyle(document.documentElement)
        .getPropertyValue(`--category-color-${i}-light`)
        .trim();

      const borderColor = getComputedStyle(document.documentElement)
        .getPropertyValue(`--category-color-${i}`)
        .trim();

      if (bgColor) {
        backgroundColors.push(bgColor);
      }

      if (borderColor) {
        borderColors.push(borderColor);
      }
    }

    return { backgroundColor: backgroundColors, borderColors };
  }

  generateHistogramData(): void {
    const min = 0;
    const max = 1000;
    const step = 100;
    const scoreRanges = this.generateScoreRanges(min, max, step);

    this.quizService.getCategories().subscribe((data: Category[]) => {
      // Inizializza per ogni categoria un array di slot
      const dataPerCategory: Record<string, number[]> = {};
      data.forEach(cat => {
        dataPerCategory[cat.name] = new Array((max - min) / step).fill(0);
      });

      // Classifica i punteggi nei rispettivi slot
      this.scores.forEach(score => {
        const rangeIndex = Math.floor(score.score / step);
        const index = Math.min(rangeIndex, (max - min) / step - 1);
        if (dataPerCategory[score.category]) {
          dataPerCategory[score.category][index]++;
        }
      });

      const { backgroundColor, borderColors } = this.getCSSColors();

      const datasets = data.map((cat, i) => ({
        label: cat.name.charAt(0).toUpperCase() + cat.name.slice(1),
        data: dataPerCategory[cat.name],
        backgroundColor: backgroundColor[i % backgroundColor.length],
        borderColor: borderColors[i % borderColors.length],
        borderWidth: 2,
        maxBarThickness: 60
      }));

      this.barChartData = {
        labels: scoreRanges,
        datasets
      };
    });
  }
  
}
<canvas baseChart
        [data]="barChartData"
        [options]="barChartOptions"
        [legend]="true"
        [type]="'bar'">
</canvas>
