// src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CategoryComponent } from '../category/category.component';
import { Category } from '../../interfaces/category.interface';
import { QuizService } from '../../services/quiz.service';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  imports: [CommonModule, FormsModule, CategoryComponent],
})
export class HomeComponent implements OnInit {
  categories: Category[] = [];
  playerName: string | null = null;
  inputName: string = '';

  constructor(private quizService: QuizService) { 
    this.playerName = localStorage.getItem('playerName');
  }

  ngOnInit(): void {
        this.quizService.getCategories().subscribe((data) => {
      this.categories = data;
    });
  }

  saveName(): void {
    if (this.inputName.trim()) {
      this.playerName = this.inputName.trim();
      localStorage.setItem('playerName', this.playerName);
    }
  }

}
<div class="page-container">
  <main class="container-fluid">
    <div class="container">

      <!-- Sezione insert name -->
      @if (!playerName) {
      <div class="row justify-content-center mb-4">
        <div class="col-12 col-lg-8">
          <div class="card shadow border-0">
            <div class="card-body text-center py-5">
              <h2 class="form-title text-center mb-4">Choose a nickname to start playing:</h2>
              <div class="mb-3 text-center">
                <label class="form-label">Your name:</label>
                <input type="text" class="form-control" [(ngModel)]="inputName" 
                       (keyup.enter)="saveName()" placeholder="Insert your name">
              </div>
              <div class="text-center">
                <button class="btn btn-primary px-4" (click)="saveName()" [disabled]="!inputName">
                  Start
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      }

      <!-- Sezione benvenuto -->
      @if (playerName) {
      <div class="row justify-content-center mb-4">
        <div class="col-12 col-lg-8">
          <div class="card shadow border-0">
            <div class="card-body text-center py-5">
              <div class="mb-4">
                <h2 class="welcome-title mb-4">Welcome, <span class="player-name">{{ playerName }}</span>!</h2>
                <p class="welcome-subtitle mb-2">Test your knowledge with QuizZap.</p>
              </div>
              <p class="welcome-subsubtitle mb-0">Choose a category and start your adventure:</p>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
          <div class="row">
            @for (category of categories; track category.name) {
            <div class="col-12 col-md-6 col-lg-4 category-item">
              <app-category [category]="category"></app-category> <!-- property binding -->
            </div>
            }
          </div>
        </div>
      </div>
      }
    </div>
  </main>
</div>

// src/components/home/Home.tsx
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getCategories } from "../../services/quiz.service";
import Category from "../category/Category";
import "./Home.css";

import type { RootState } from "../../redux/store";
import { setPlayerName } from "../../redux/playerSlice";
import type { Category as CategoryType } from "../../interfaces/category.interface";

function Home() {
  const dispatch = useDispatch();
  const playerName = useSelector((state: RootState) => state.player.name);
  const [inputName, setInputName] = useState("");
  const [categories, setCategories] = useState<CategoryType[]>([]);

  useEffect(() => {
    getCategories().then((data) => setCategories(data));
  }, []);

  function saveName() {
    const trimmed = inputName.trim();
    if (trimmed) {
      dispatch(setPlayerName(trimmed)); // aggiorna stato globale
      setInputName("");
    }
  }

  return (
    <div className="page-container">
      <main className="container-fluid">
        <div className="container">
          {!playerName && (
            <div className="row justify-content-center mb-4">
              <div className="col-12 col-lg-8">
                <div className="card shadow border-0">
                  <div className="card-body text-center py-5">
                    <h2 className="form-title text-center mb-4">Choose a nickname to start playing:</h2>
                    <div className="mb-3 text-center">
                      <label className="form-label">Your name:</label>
                      <input
                        type="text"
                        className="form-control"
                        value={inputName}
                        onChange={(e) => setInputName(e.target.value)}
                        onKeyDown={(e) => e.key === "Enter" && saveName()}
                        placeholder="Insert your name"
                      />
                    </div>
                    <div className="text-center">
                      <button
                        className="btn btn-primary px-4"
                        onClick={saveName}
                        disabled={!inputName.trim()}
                      >
                        Start
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {playerName && (
            <>
              <div className="row justify-content-center mb-4">
                <div className="col-12 col-lg-8">
                  <div className="card shadow border-0">
                    <div className="card-body text-center py-5">
                      <div className="mb-4">
                        <h2 className="welcome-title mb-4">
                          Welcome, <span className="player-name">{playerName}</span>!
                        </h2>
                        <p className="welcome-subtitle mb-2">Test your knowledge with QuizZap.</p>
                      </div>
                      <p className="welcome-subsubtitle mb-0">Choose a category and start your adventure:</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="row justify-content-center">
                <div className="col-12 col-lg-10">
                  <div className="row">
                    {categories.map((category) => (
                      <div key={category.id} className="col-12 col-md-6 col-lg-4 category-item">
                        <Category category={category} />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      </main>
    </div>
  );
}

export default Home;
