// src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive} from '@angular/router';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  imports: [MatIconModule, RouterLink, RouterLinkActive],
})
export class HeaderComponent {

}
<nav class="navbar navbar-expand-md navbar-light bg-white header shadow-sm">
  <div class="container-fluid">
    <div class="navbar-brand d-flex align-items-center">
      <img src="../../assets/logo.png" alt="Logo" class="logo-image me-3" />
      <span class="logo">QuizZap</span>
    </div>
    
    <div class="navbar-nav ms-auto nav-buttons">
      <a class="nav-link" routerLink="/" routerLinkActive="active-link" 
         [routerLinkActiveOptions]="{ exact: true }">
        <i class="material-icons">home</i>
        Home
      </a>
      <a class="nav-link" routerLink="/leaderboard" routerLinkActive="active-link"
         [routerLinkActiveOptions]="{ exact: false }">
        <i class="material-icons">leaderboard</i>
        Leaderboard
      </a>
    </div>
  </div>
</nav>

// src/components/Header.tsx
import { NavLink } from "react-router-dom";
import Logo from '../assets/logo.png'

import './Header.css'

function Header() {

  return (
    <>
      <nav className="navbar navbar-expand-md navbar-light bg-white header shadow-sm">
        <div className="container-fluid">
          <div className="navbar-brand d-flex align-items-center">
            <img src={Logo} alt="Logo" className="logo-image me-3" />
            <span className="logo">QuizZap</span>
          </div>

          <div className="navbar-nav ms-auto nav-buttons">
            <NavLink
              to="/"
              className={({ isActive }) => "nav-link" + (isActive ? " active-link" : "")}
              end
            >
              <i className="material-icons">home</i> Home
            </NavLink>

            <NavLink
              to="/leaderboard"
              className={({ isActive }) => "nav-link" + (isActive ? " active-link" : "")}
            >
              <i className="material-icons">leaderboard</i> Leaderboard
            </NavLink>
          </div>
        </div>
      </nav>
    </>
  );
}

export default Header
