// src/app/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, Router} from '@angular/router';

import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  imports: [MatToolbarModule, MatButtonModule, MatIconModule, RouterLink, RouterLinkActive],
})
export class HeaderComponent {

  constructor(private router: Router) {
    this.router.events.subscribe(() => {
      const url = this.router.url;
      const match = url.match(/^\/leaderboard\/.+/);
      
    });
  }
}
<mat-toolbar color="primary" class="header">
  <div class="header-content">
    <img src="../../assets/logo.png" alt="Logo" class="logo-image" />
    <span class="logo">QuizZap</span>
    
    <div class="nav-buttons">
      <a mat-button routerLink="/" routerLinkActive="active-link" 
      [routerLinkActiveOptions]="{ exact: true }">
        <mat-icon>home</mat-icon>
        Home
      </a>
      <a mat-button routerLink="/leaderboard" routerLinkActive="active-link"
      [routerLinkActiveOptions]="{ exact: false }">
        <mat-icon>leaderboard</mat-icon>
        Leaderboard
      </a>
    </div>
  </div>
</mat-toolbar>

// src/components/Header.tsx
import { NavLink } from "react-router-dom";
import Logo from '../assets/logo.png'

import './Header.css'

function Header() {

  return (
    <>
      <nav className="navbar navbar-expand-md navbar-light bg-white header shadow-sm">
        <div className="container-fluid">
          <div className="navbar-brand d-flex align-items-center">
            <img src={Logo} alt="Logo" className="logo-image me-3" />
            <span className="logo">QuizZap</span>
          </div>

          <div className="navbar-nav ms-auto nav-buttons">
            <NavLink
              to="/"
              className={({ isActive }) => "nav-link" + (isActive ? " active-link" : "")}
              end
            >
              <i className="material-icons">home</i> Home
            </NavLink>

            <NavLink
              to="/leaderboard"
              className={({ isActive }) => "nav-link" + (isActive ? " active-link" : "")}
            >
              <i className="material-icons">leaderboard</i> Leaderboard
            </NavLink>
          </div>
        </div>
      </nav>
    </>
  );
}

export default Header
