// src/components/results/Results.tsx
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import type { RootState } from "../../redux/store";
import { resetQuiz } from "../../redux/quizSlice";
import { saveScore } from "../../services/score.service";
import type { Question } from "../../interfaces/question.interface";
import { formatTitleCase } from "../../utils/format";
import { formatTime } from "../../utils/format";
import "./Results.css";

function Results() {
  const { category } = useParams<{ category: string }>(); // prendo categoria da url
  const navigate = useNavigate();
  const dispatch = useDispatch();

  // prende i dati dallo store redux
  const {
    questions,
    correctAnswers,
    finalScore,
    remainingTime,
    selectedCategory,
    isQuizCompleted
  } = useSelector((state: RootState) => state.quiz);

  const playerName = useSelector((state: RootState) => state.player.name);

  const [scoreSaved, setScoreSaved] = useState(false);

  const scoreKey = `${playerName}_${category}_${finalScore}`;

  useEffect(() => {
    if (isQuizCompleted && questions.length > 0) {
      // Caso normale - dati nello store
      return;
    }

    // Caso refresh - prova a recuperare da sessionStorage
    const savedResult = sessionStorage.getItem(`quiz_result_${category}`);
    if (savedResult) {
      const resultData = JSON.parse(savedResult);

      setScoreSaved(resultData);
      return;
    };

    // Se non ci sono dati validi, vai alla home
    navigate("/");
  }, [category, isQuizCompleted, questions.length]);

  function getScoreMessage(): string {
    const percentage = Math.round((correctAnswers / questions.length) * 100);
    if (percentage >= 90) return "Excellent!";
    if (percentage >= 70) return "Great job!";
    if (percentage >= 50) return "Good result!";
    return "Keep going!";
  }

  function handleSaveScore(): void {
    if (scoreSaved) return;

    const scoreData = {
      username: playerName,
      category: category || "",
      score: finalScore,
      date: new Date(),
    };

    saveScore(scoreData)
      .then(() => {
        console.log("Score saved successfully");
        setScoreSaved(true);
        localStorage.setItem(scoreKey, "saved");
      })
      .catch((error) => {
        console.error("Error saving score:", error);
      });
  }

  function isAnswerCorrect(question: Question): boolean {
    return question.currentAnswer === question.correctOptionIndex;
  }

  function handleRestartQuiz(): void {
    // reset dello stato redux prima di riavviare il quiz
    dispatch(resetQuiz());
    navigate(`/quiz/${category}`);
    window.scrollTo(0, 0);
  }

  function handleViewLeaderboard(): void {
    navigate(`/leaderboard/${category}`);
    window.scrollTo(0, 0);
  }

  function handleBackToCategories(): void {
    // reset dello stato redux quando si torna alla home
    dispatch(resetQuiz());
    navigate("/");
    window.scrollTo(0, 0);
  }

  // Se non ci sono dati del quiz, non renderizzare nulla
  if (!isQuizCompleted || questions.length === 0) {
    return null;
  }

  return (
    <div className="result-container">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-12 col-lg-10">
            <div className="card result-main-card shadow border-0">

              <div className="result-header">
                <h1>{formatTitleCase(selectedCategory)} Quiz Results</h1>
              </div>

              <div className="result-content">
                <div className="quiz-results">
                  <h3>{getScoreMessage()}</h3>

                  <div className="score-summary mb-0 mt-0">
                    <div className="score-item">
                      <strong>Correct Answers:</strong> {correctAnswers} / {questions.length}
                    </div>
                    <div className="score-item">
                      <strong>Final Score:</strong> {finalScore} points
                    </div>
                    <div className="score-item">
                      <strong>Remaining Time:</strong> {formatTime(remainingTime)}
                    </div>
                    <div className="score-actions">
                      <button
                        type="button"
                        className="btn btn-light"
                        onClick={handleSaveScore}
                        disabled={scoreSaved}
                      >
                        {scoreSaved ? 'Score Saved!' : 'Save Score'}
                      </button>
                    </div>
                  </div>

                  <div className="answers-review mt-4 mb-0">
                    <h2>Answers review:</h2>
                    {questions.map((question, i) => (
                      <div key={question.id} className="question-review">
                        <h4>Question {i + 1}: {question.question}</h4>

                        <div className="review-options">
                          {question.options.map((option, optionIndex) => {
                            const isCorrect = optionIndex === question.correctOptionIndex;
                            const isUserAnswer = optionIndex === question.currentAnswer;
                            const isWrongAnswer = isUserAnswer && !isAnswerCorrect(question);

                            return (
                              <div
                                key={optionIndex}
                                className={`review-option ${isCorrect ? 'correct' : ''} ${isWrongAnswer ? 'wrong' : ''}`}
                              >
                                {option}
                                {isCorrect && (
                                  <span className="correct-label"> (Correct)</span>
                                )}
                                {isWrongAnswer && (
                                  <span className="wrong-label"> (Your answer)</span>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Azioni Finali */}
                  <div className="final-actions">
                    <button
                      type="button"
                      className="btn btn-light"
                      onClick={handleViewLeaderboard}
                    >
                      {formatTitleCase(selectedCategory)} Leaderboard
                    </button>
                    <button
                      type="button"
                      className="btn btn-light"
                      onClick={handleRestartQuiz}
                    >
                      Restart Quiz
                    </button>
                    <button
                      type="button"
                      className="btn btn-light"
                      onClick={handleBackToCategories}
                    >
                      Back to Categories
                    </button>
                  </div>

                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Results;

// src/app/components/results/results.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';

import { Question } from '../../interfaces/question.interface';
import { Score } from '../../interfaces/score.interface';
import { ScoreService } from '../../services/score.service';

interface QuizResults {
  questions: Question[];
  correctAnswers: number;
  finalScore: number;
  remainingTime: number;
  selectedCategory: string;
  currentCategoryId: number;
}

@Component({
  selector: 'app-results',
  standalone: true,
  templateUrl: './results.component.html',
  styleUrl: './results.component.css',
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule
  ],
})
export class ResultsComponent implements OnInit {
  questions: Question[] = [];
  correctAnswers = 0;
  finalScore = 0;
  remainingTime = 0;
  selectedCategory = '';
  currentCategoryId = 0;
  playerName = '';
  scoreSaved = false;

  constructor(
    private scoreService: ScoreService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.playerName = localStorage.getItem('playerName') || '';

    this.route.params.subscribe(params => {
      this.selectedCategory = params['category'];
    });

    // Recupera i dati dai parametri di navigazione
    const state = history?.state as QuizResults;

    if (state) {
      this.questions = state.questions;
      this.correctAnswers = state.correctAnswers;
      this.finalScore = state.finalScore;
      this.remainingTime = state.remainingTime;
      this.currentCategoryId = state.currentCategoryId;

      // Controlla se questo specifico punteggio è già stato salvato
      const scoreKey = `${this.playerName}_${this.selectedCategory}_${this.finalScore}`;
      this.scoreSaved = localStorage.getItem(scoreKey) === 'saved';
    } else {
      // Se non ci sono dati, reindirizza alla home
      this.router.navigate(['/']);
    }
  }

  getScoreMessage(): string {
    const percentage = Math.round((this.correctAnswers / this.questions.length) * 100);
    if (percentage >= 90) return 'Excellent!';
    if (percentage >= 70) return 'Great job!';
    if (percentage >= 50) return 'Good result!';
    return 'Keep going!';
  }

  saveScore(): void {
    if (this.scoreSaved) return;

    const scoreData = {
      username: this.playerName,
      category: this.selectedCategory,
      score: this.finalScore,
      date: new Date()
    };

    this.scoreService.saveScore(scoreData).subscribe({
      next: () => {
        console.log('Score saved successfully');
        this.scoreSaved = true;

        // Salva nel localStorage per prevenire salvataggi futuri dello stesso punteggio
        const scoreKey = `${this.playerName}_${this.selectedCategory}_${this.finalScore}`;
        localStorage.setItem(scoreKey, 'saved');
      },
      error: (error) => {
        console.error('Error saving score:', error);
        // Non modificare scoreSaved in caso di errore per permettere un nuovo tentativo
      }
    });
  }

  isAnswerCorrect(questionIndex: number): boolean {
    const question = this.questions[questionIndex];
    return question.currentAnswer === question.correctOptionIndex;
  }

  restartQuiz(): void {
    this.router.navigate(['/quiz', this.selectedCategory]);
  }

  viewCategoryLeaderboard(): void {
    this.router.navigate(['/leaderboard', this.selectedCategory]);
  }

  goBackToCategories(): void {
    this.router.navigate(['/']);
  }
}

<div class="result-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10">
        <div class="card result-main-card shadow border-0">

          <!-- Result Header -->
          <div class="result-header">
            <h1>{{ selectedCategory | titlecase }} Quiz Results</h1>
          </div>

          <div class="result-content">
            <!-- Risultati del Quiz -->
            <div class="quiz-results">
              <h3>{{ getScoreMessage() }}</h3>

              <div class="score-summary mb-0 mt-0">
                <div class="score-item">
                  <strong>Correct Answers:</strong> {{ correctAnswers }} / {{ questions.length }}
                </div>
                <div class="score-item">
                  <strong>Final Score:</strong> {{ finalScore }} points
                </div>
                <div class="score-item">
                  <strong>Remaining Time:</strong> {{ (remainingTime * 1000) | date:'mm:ss':'UTC' }}
                </div>
                <div class="score-actions">
                  <button type="button" class="btn btn-light" (click)="saveScore()" [disabled]="scoreSaved">
                    {{ scoreSaved ? 'Score Saved!' : 'Save Score' }}
                  </button>
                </div>
              </div>

              <!-- Revisione Risposte -->
              <div class="answers-review mt-4 mb-0">
                <h2>Answers review:</h2>
                @for (question of questions; track question.id; let i = $index) {
                <div class="question-review">
                  <h4>Question {{ i + 1 }}: {{ question.question }}</h4>

                  <div class="review-options">
                    @for (option of question.options; track $index; let optionIndex = $index) {
                    <div class="review-option" [ngClass]="{
                        'correct': optionIndex === question.correctOptionIndex,
                        'wrong': optionIndex === question.currentAnswer && !isAnswerCorrect(i)
                      }">
                      {{ option }}
                      @if (optionIndex === question.correctOptionIndex) {
                      <span class="correct-label">(Correct)</span>
                      }
                      @if (optionIndex === question.currentAnswer && !isAnswerCorrect(i)) {
                      <span class="wrong-label">(Your answer)</span>
                      }
                    </div>
                    }
                  </div>
                </div>
                }
              </div>

              <!-- Azioni Finali -->
              <div class="final-actions">
                <button type="button" class="btn btn-light" (click)="viewCategoryLeaderboard()">
                  {{ selectedCategory | titlecase }} Leaderboard
                </button>
                <button type="button" class="btn btn-light" (click)="restartQuiz()">
                  Restart Quiz
                </button>
                <button type="button" class="btn btn-light" (click)="goBackToCategories()">
                  Back to Categories
                </button>
              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
